home/urls.py
from django.conf.urls import url

from . import views

app_name = 'home'

urlpatterns = [

    # Register User
    url(r'register/$', views.register, name="register"),
    # - Get Information from user
    url(r'information/$', views.get_information, name="get_information"),
    # - Dashboard
    url(r'dashboard/$', views.dashboard, name='dashboard'),
    # /-Sends to home page
    url(r'^$', views.home_page, name="home_page"),
    # /schedule - Get Information from user
    url(r'schedule/$', views.schedule, name="schedule"),
    # /test_send_email
    url(r'test_send_email/$', views.test_send_email, name='test_send_email'),
    # /points_table - Gets the points table
    url(r'points_table/(?P<pool_number>[0-9]+)/$', views.points_table, name='points_table'),
    # /schedule/(pool_number)
    url(r'schedule/(?P<pool_number>[0-9]+)/$', views.schedule, name="pool_schedule"),
    #/logout
    url(r'logout/$', views.logout, name="logout")

]

match_scheduler/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('home.urls')),
    url(r'^admin/', admin.site.urls),

]

home/models.py
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator
from django.db import models


# Create your models here.
class UserWrapper(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, unique=True)


class Tournament(models.Model):
    login = models.ForeignKey(UserWrapper, on_delete=models.CASCADE)
    matches_per_day = models.PositiveIntegerField(validators=[MaxValueValidator(100)])
    number_of_team = models.IntegerField(validators=[MaxValueValidator(50)])
    number_of_pool = models.IntegerField(default=1)
    type = models.IntegerField()
    available_days = models.IntegerField()

    def __str__(self):
        return str(self.id) + ' ' + str(self.type)


class Pool(models.Model):
    tournament = models.ForeignKey(Tournament, on_delete=models.CASCADE)
    pool_number = models.IntegerField(default=1)
    number_of_teams = models.IntegerField()


class Point(models.Model):
    pool = models.ForeignKey(Pool, on_delete=models.CASCADE, default=None)
    team = models.CharField(max_length=100)
    wins = models.IntegerField(default=0)

    def __str__(self):
        return self.team + "-" + str(self.wins)


class Match(models.Model):
    pool = models.ForeignKey(Pool, on_delete=models.CASCADE, default=None)
    team1 = models.CharField(max_length=100)
    team2 = models.CharField(max_length=100)
    winner = models.CharField(max_length=1, default='0')

    def __str__(self):
        return str(self.pk) + self.team1 + "V/S" + self.team2 + "->" + self.winner

home/forms.py
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from .models import Tournament


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ['username', 'email', 'password', 'first_name', 'last_name']
        labels = {
            'username': _('User Name'),
            'email' : _('E-Mail'),
            'password' : _('Password'),
            'first_name': _('First Name'),
            'last_name' : _('Last Name')
        }


class TournamentForm(forms.ModelForm):
    match_type = forms.ChoiceField(choices=[('League Match', 'League Match'),(('Pool Match', 'Pool Match'))])  # , 'Knockout Match'])
    class Meta:
        model = Tournament
        fields = ['matches_per_day', 'number_of_team', 'number_of_pool','available_days']
        labels = {
            'matches_per_day': _('Matches per day'),
            'number_of_team': _('Number of Teams'),
            'number_of_pool' : _('Number of Pools'),
            'available_days':_('Available Days')
        }

home/views.py
import math

from django.conf import settings
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.shortcuts import render, HttpResponse

from .forms import TournamentForm, UserForm
from .models import Match, Point, Pool, UserWrapper


def user_logged_in(request):
    user_id = request.session.get('user_id', 0)
    if not user_id:
        return 0
    else:
        return user_id


# Basic home page(information about spofit)
def get_information(request):
    user_id = user_logged_in(request)
    if user_id:
        if request.method == "POST":
            form = TournamentForm(request.POST)
            if form.is_valid():
                tournament = form.save(commit=False)
                user_obj = User.objects.get(pk=user_id)
                user_wrapper = user_obj.userwrapper
                tournament.login = user_wrapper
                print(user_wrapper.user.username)
                type_of_match = form.cleaned_data.get('match_type')
                type = 1
                if type_of_match == 'Pool Match':
                    type = 2
                tournament.type = type
                tournament.save()
                group1 = []
                group2 = []
                list1 = []
                list2 = []
                user_name = user_obj.username

                number_of_teams = tournament.number_of_team
                number_of_days = tournament.available_days
                matches_per_day = tournament.matches_per_day
                number_of_pool = tournament.number_of_pool
                # Our conventions
                # 1. League matches
                # 2. Pool System
                # 3. Knockout

                # League matches
                print("scheduling")
                print(type)
                if type == 1:
                    number_of_matches = (number_of_teams * (number_of_teams - 1) / 2)
                    minimum_days = int(math.ceil(number_of_matches / matches_per_day))

                    if number_of_days < minimum_days:
                        return HttpResponse(
                            "Sorry Matches cant be schedule in " + str(
                                number_of_days) + " days but can be scheduled in " + str(
                                minimum_days))
                    odd = False

                    # new_user = LoginCredential(user_name=user_name, password=password, matches_per_day=matches_per_day,
                    #                            number_of_team=number_of_teams, type=type, number_of_pool=1)
                    # new_user.save()
                    # new_pool = Pool(login=new_user, pool_number=1)
                    # new_pool.save()
                    # user_id = new_user.id
                    if number_of_teams % 2 == 1:
                        odd = True
                        number_of_teams += 1
                    # group1=["pune warriors india","Mumbai Indian","King X1 punjab","Sunrise Hyderbad"]
                    # group2=["Rising Pune Supergaints","Chennai king","Kolkalta Kinight rider","Delhi devils"]
                    for i in range(1, int(number_of_teams / 2) + 1):
                        group1.append("Team" + str(i))
                        group2.append("Team" + str(i + int(number_of_teams / 2)))

                    # print(group1)
                    # print(group2)
                    for i in range(number_of_teams - 1):
                        list1.extend(group1)
                        list2.extend(group2)
                        group1.insert(1, group2[0])
                        group2.remove(group2[0])
                        group2.append(group1[int(number_of_teams / 2)])
                        group1.remove(group1[int(number_of_teams / 2)])

                    all_new_teams = []
                    pool = Pool(tournament=tournament, number_of_teams=number_of_teams, pool_number=1)
                    pool.save()
                    for team in group1:
                        all_new_teams.append(Point(pool=pool, team=team))

                    for team in group2[:-1]:
                        all_new_teams.append(Point(team=team, pool=pool))
                    # Using bulk_create instead of saving team every time
                    # It uses only one query to save all teams
                    # Silimarly for all the matches we used save n*(n-1)/2 times but now will use only 1 query
                    # Very much optimized
                    Point.objects.bulk_create(all_new_teams)

                    if not odd:
                        new_team = Point(team=group2[len(group2) - 1], pool=pool)
                        new_team.save()
                    if odd:
                        index = list1.index("Team" + str(number_of_teams))
                        while index:
                            list1.pop(index)
                            list2.pop(index)
                            try:
                                index = list1.index("Team" + str(number_of_teams))
                            except:
                                break

                        index = list2.index("Team" + str(number_of_teams))
                        while index:
                            list1.pop(index)
                            list2.pop(index)
                            try:
                                index = list2.index("Team" + str(number_of_teams))
                            except:
                                break
                    # all_matches = zip(list1,list2)
                    # print(minimum_days)
                    # print(matches_per_day)
                    # print(list1)
                    # print(list2)
                    new_matches = []
                    for i in range(len(list1)):
                        new_matches.append(Match(team1=list1[i], team2=list2[i], pool=pool))
                        # print(new_matches[i].id)
                    Match.objects.bulk_create(new_matches)
                    # match_id_list = list(Match.objects.filter(login=new_user).values_list('id', flat=True))
                    # print(match_id_list)
                    # Set user id for this session
                    # Acess using (user_id = request.session['user_id'])
                    match_obj_rows = pool.match_set
                    match_id_list = match_obj_rows.values_list('id', flat=True)
                    print(list1)
                    return HttpResponseRedirect('/schedule/')
                # Pool system
                elif type == 2:
                    if number_of_teams >= 8:
                        if number_of_teams % 3 == 0 or number_of_teams % 4 == 0 or number_of_teams % 5 == 0:

                            team_per_pool = int(number_of_teams / number_of_pool)
                            # if number_of_teams % 6 == 0:
                            #     team_per_pool = 6
                            # elif number_of_teams % 5 == 0:
                            #     team_per_pool = 5
                            # elif number_of_teams % 4 == 0:
                            #     team_per_pool = 4
                            # elif number_of_teams % 3 == 0:
                            #     team_per_pool = 3
                            # number_of_pool = int(number_of_teams / team_per_pool)

                            number_of_matches = int(
                                (team_per_pool * (team_per_pool - 1)) / 2) * number_of_pool
                            new_pool = []
                            new_points_table = []
                            for i in range(number_of_pool):
                                new_pool += [
                                    Pool(tournament=tournament, pool_number=i + 1,
                                         number_of_teams=team_per_pool
                                         )]
                                # print(new_pool[i].pk)
                            Pool.objects.bulk_create(new_pool)
                            print(new_pool)
                            all_teams = []
                            for i in range(1, number_of_teams + 1):
                                all_teams.append("Team" + str(i))
                            # all_teams = group1 + group2
                            # print(all_teams)
                            all_pool = Pool.objects.filter(tournament=tournament)
                            for i in range(number_of_pool):
                                for j in range(team_per_pool):
                                    # print(new_pool[i].id)
                                    new_points_table += [Point(pool=all_pool[i], team=all_teams[i * team_per_pool + j])]
                                    # print(str(i) + ' ' + all_teams[i * team_per_pool + j])
                            Point.objects.bulk_create(new_points_table)

                            new_matches = []
                            list1 = []
                            list2 = []
                            for i in range(number_of_pool):
                                zipped_list = round_robin(
                                    list(Point.objects.filter(pool=all_pool[i]).values_list('team', flat=True)))
                                for team1, team2 in zipped_list:
                                    print(team1 + "v/s" + team2)
                                    list1.append(team1)
                                    list2.append(team2)
                                    new_matches.append(Match(pool=all_pool[i], team1=team1, team2=team2))

                            Match.objects.bulk_create(new_matches)
                            rows = int(math.floor(number_of_pool / 2))
                            extra = 0
                            if number_of_pool % 2 == 1:
                                extra = number_of_pool - 1

home/templates/home/bootstrap.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {#    {% load static %}#}
    <title>Match Scheduler</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <style>
        body {
            padding-top: 50px;
            background: #F1F1F1;
        }

        #main {
            height: 100%;
            overflow: auto;
        }

        .navbar {
            background: #ce0010;
        }

        .navbar-custom .navbar-nav > li > a:hover {
            background: #b3000f;
        }

        .navbar-custom .navbar-nav > li > a, .navbar-custom .navbar-brand {
            color: #ffffff;
        }

        .navbar-custom {
            border: #ffffff;
        }

        .selected {
            background: #b3000f;
            color: #FFFFFF !important;
        }

        .nav-pills > li > a {
            color: #000000;
        }

        .navbar-brand {
            font-size: 1.7em;
        }

        .navbar-right {
            margin-right: 15px;
            margin-top: 15px;
            color: #FFFFFF;
        }

        .icon-bar {
            background: #fff;
        }

        {% block style %}
        {% endblock %}
    </style>
    {% block head %}
    {% endblock %}

</head>
<body>

<!--Navbar top-->

<div class="navbar navbar-custom navbar-fixed-top">
    <div class="navbar-header">
        <!--Button NAVBAR toggle-->
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">SpoFit</a>
    </div>
    <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
            <li><a class="selected" href="#">Home</a></li>
            <li><a href="#">Contact Info</a></li>
            {#            {% block navbar_left %}#}
            {% if logged_in %}

                <li><a href="{% url 'home:get_information' %}">Add</a></li>
            {% else %}
                <li><a href="{% url 'home:register' %}">Registration</a></li>
            {% endif %}

            {#            {% endblock %}#}
            {% block navbar_left %}
            {% endblock %}
        </ul>
        {% block navbar_right %}
        {% endblock %}
    </div>
</div>
{% block body %}
{% endblock %}
</body>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>

<script>
    $(document).ready(function () {
        $('[data-toggle=offcanvas]').click(function () {
            $('.row-offcanvas').toggleClass('active');
        });
    });
</script>
</html>

home/templates/home/dashboard.html
{% extends 'home/bootstrap.html' %}
{% load static %}
{% load widget_tweaks %}
{% block head %}
    <style>
        body, html, .row-offcanvas {
            height: 100%;
        }

        body {
            padding-top: 50px;
            background: #F1F1F1;
        }

        #sidebar {
            width: inherit;
            min-width: 220px;
            max-width: 220px;
            background-color: #F1F1F1;
            float: left;
            height: 100%;
            position: relative;
            overflow-y: auto;
            overflow-x: hidden;
        }

        #main {
            height: 100%;
            overflow: auto;
        }

        /*Media query for small screen toggle*/
        @media screen and (max-width: 768px) {
            .row-offcanvas {
                position: relative;
                -webkit-transition: all 0.25s ease-out;
                -moz-transition: all 0.25s ease-out;
                transition: all 0.25s ease-out;
                width: calc(100% + 220px);
            }

            .row-offcanvas-left {
                left: -220px;
            }

            .row-offcanvas-left.active {
                left: 0;
            }

            .sidebar-offcanvas {
                position: absolute;
                top: 0;
            }
        }

        /*Media query for small screen toggle ENDS*/

        /*Extra style for main contents div*/
        .back {
            background: #ffffff;
            height: 100%;
        }

        .nav-stacked {
            padding-top: 5px;
        }

    </style>
{% endblock %}
{% block navbar_right %}
    <form action="{% url 'home:logout' %}" method="post">
        {% csrf_token %}
        <div style="margin-top: 7px;margin-right: 5px;float: right">
            <button type="submit" name="logout" value="logout">Logout</button>
        </div>
    </form>

{% endblock %}
{% block body %}


    <!--Body with side navbar and main content-->

    <div class="row-offcanvas row-offcanvas-left">
        <!--Sidebar navigation-->
        <div id="sidebar" class="sidebar-offcanvas">
            <div class="col-md-12 back">
                <ul class="nav nav-pills nav-stacked">
                    <li><a class="selected" href="#">Dashboard</a></li>

                    {% if number_of_pool > 1 %}
                        <li><a href="{% url 'home:pool_schedule' pool_number=0 %}">Pool</a></li>
                    {% else %}
                        <li><a href="{% url 'home:schedule' %}">Schedule</a></li>
                        <li><a href="#">Points Table</a></li>
                    {% endif %}

                    <li><a href="#">Result</a></li>
                    <li><a href="#">Section</a></li>
                    <li><a href="#">F.A.Q</a></li>
                </ul>
            </div>
        </div>
        <!--Main content-->
        <div id="main">
            <div class="col-md-8">
                <!--Toggle for sidebar nav-->
                <p class="visible-xs">
                    <button type="button" class="btn btn-danger btn-sm" data-toggle="offcanvas">
                        <i class="glyphicon glyphicon-chevron-left"></i>
                    </button>
                </p>


            </div>

        </div>
    </div>

    </div>

{% endblock %}

home/templates/home/points_table.html
{% extends 'home/bootstrap.html' %}
{% block style %}
    .thead-inverse{
    background:#b3000f;
    color:#fff;
    }body, html, .row-offcanvas {
    height: 100%;
    }

    body {
    padding-top: 50px;
    background: #f5f5f5;
    }

    #sidebar {
    width: inherit;
    min-width: 220px;
    max-width: 220px;
    background-color: #f5f5f5;
    float: left;
    height: 100%;
    position: relative;
    overflow-y: auto;
    overflow-x: hidden;
    }

    #main {
    height: 100%;
    overflow: auto;
    }

    .navbar {
    background: #ce0010;
    }

    .navbar-inverse .navbar-nav > li > a:hover {
    background: #b3000f;
    }

    .navbar-inverse .navbar-nav > li > a, .navbar-inverse .navbar-brand {
    color: #ffffff;
    }

    .navbar-inverse {
    border: #ffffff;
    }

    .navbar-inverse .navbar-nav > .active > a, .navbar-inverse .navbar-nav > .active > a:hover {
    background: #b3000f;
    }

    .nav-pills > li.active > a, .nav-pills > li.active > a:hover {
    background: #b3000f;
    }

    .nav-pills > li > a {
    color: #000000;
    }

    .bolder {
    font-weight: bolder;
    }

    .wrap {
    background: #fff;
    margin-bottom: 20px;
    }

    .left-border {
    padding: 5px;
    border-left: 3px solid #ce0010;
    }

    .white {
    background: #FFF;
    box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);
    margin-top: 10px
    }

    .back {
    background: #ffffff;
    height: 100%;
    }

    .nav-stacked {
    padding-top: 5px;
    }

    /*
    * off Canvas sidebar
    * --------------------------------------------------
    */
    @media screen and (max-width: 768px) {
    .row-offcanvas {
    position: relative;
    -webkit-transition: all 0.25s ease-out;
    -moz-transition: all 0.25s ease-out;
    transition: all 0.25s ease-out;
    width: calc(100% + 220px);
    }

    .row-offcanvas-left {
    left: -220px;
    }

    .row-offcanvas-left.active {
    left: 0;
    }

    .sidebar-offcanvas {
    position: absolute;
    top: 0;
    }
    }
{% endblock %}
{% block body %}
    <div class="row-offcanvas row-offcanvas-left">
        <div id="sidebar" class="sidebar-offcanvas">
            <div class="col-md-12 back">
                <form action="{% url 'home:schedule' %}" method="get">
                    <ul class="nav nav-pills nav-stacked">
                        <li><a href="{% url 'home:dashboard' %}">Dashboard</a></li>
                        {% if number_of_pool > 1 %}
                            <li><a href="{% url 'home:pool_schedule' 0 %}">Pool</a></li>
                        {% endif %}
                        <li class="active"><a href="{% url 'home:pool_schedule' pool_number %}">Schedule</a></li>
                        <li><a href="{% url 'home:points_table' pool_number %}">Points Table</a></li>
                        <li><a href="#">Result</a></li>
                        <li><a href="#">Section</a></li>
                        <li><a href="#">F.A.Q</a></li>
                    </ul>
                </form>
            </div>
        </div>

        <div id="main">
            <div class="col-md-12">
                <p class="visible-xs">
                    <button type="button" class="btn btn-danger btn-sm" data-toggle="offcanvas"><i
                            class="glyphicon glyphicon-chevron-left"></i></button>
                </p>
                <div class="table-responsive">
                    <table class="table table-bordered white">
                        <thead class="thead-inverse">
                        <tr>

                            <th>Team</th>
                            <th>Points</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for team in full_table %}

                            <tr>
                                <td>{{ team.team }}</td>
                                <td>{{ team.wins }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

home/templates/home/pool.html
{% extends 'home/bootstrap.html' %}
{% load extra %}
{% block style %}
    .thead-inverse{
    background:#b3000f;
    color:#fff;
    }body, html, .row-offcanvas {
    height: 100%;
    }


    #sidebar {
    width: inherit;
    min-width: 220px;
    max-width: 220px;
    background-color: #f5f5f5;
    float: left;
    height: 100%;
    position: relative;
    overflow-y: auto;
    overflow-x: hidden;
    }

    #main {
    height: 100%;
    overflow: auto;
    }
    .nav-pills > li.active > a{
    background:#b3000f;
    }
    .bolder {
    font-weight: bolder;
    }

    .wrap {
    background: #fff;
    margin-bottom: 20px;
    }

    .left-border {
    padding: 5px;
    border-left: 3px solid #ce0010;
    }

    .white {
    background: #FFF;
    box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);
    margin-top: 10px
    }

    .back {
    background: #ffffff;
    height: 100%;
    }

    .nav-stacked {
    padding-top: 5px;
    }

    /*
    * off Canvas sidebar
    * --------------------------------------------------
    */
    @media screen and (max-width: 768px) {
    .row-offcanvas {
    position: relative;
    -webkit-transition: all 0.25s ease-out;
    -moz-transition: all 0.25s ease-out;
    transition: all 0.25s ease-out;
    width: calc(100% + 220px);
    }

    .row-offcanvas-left {
    left: -220px;
    }

    .row-offcanvas-left.active {
    left: 0;
    }

    .sidebar-offcanvas {
    position: absolute;
    top: 0;
    }
    }
    .pool-title{
    text-align:center;
    }
{% endblock %}
{% block body %}
    <div class="row-offcanvas row-offcanvas-left">
        <div id="sidebar" class="sidebar-offcanvas">
            <div class="col-md-12 back">
                <form action="{% url 'home:schedule' %}" method="get">
                    <ul class="nav nav-pills nav-stacked">
                        <li><a href="{% url 'home:dashboard' %}"> Dashboard</a></li>
                        <li class="active"><a href="{% url 'home:pool_schedule' 0 %}">Pool</a></li>
{#                        <li disabled="disabled"><a href="{% url 'home:points_table' 0 %}">Points Table</a></li>#}
                        <li><a href="#">Result</a></li>
                        <li><a href="#">Section</a></li>
                        <li><a href="#">F.A.Q</a></li>
                    </ul>
                </form>
            </div>
        </div>

        <div id="main">
            <div class="col-md-12">
                <p class="visible-xs">
                    <button type="button" class="btn btn-danger btn-sm" data-toggle="offcanvas"><i
                            class="glyphicon glyphicon-chevron-left"></i></button>
                </p>
                <form action="{% url 'home:schedule' %}" method="post">
                    {% csrf_token %}
                    {% for i in rows %}
                        <div class="row">
                            {% for j in "01" %}
                                <div class="col-lg-6">
                                    <table class="table table-bordered white">
                                        <tr>
                                            <th class="pool-title" colspan="2">
                                                <button style="width: 100%;font-size: 1.1em; height: 100%; background-color: inherit; padding: 5px; border: none"
                                                        class="pool-title" name="Pool"
                                                        value="{% index_calculator forloop.parentloop.counter0 forloop.counter0 2 %}">
                                                    Pool {% index_calculator forloop.parentloop.counter0 forloop.counter0 2 %}</button>
                                            </th>

                                        </tr>
                                        <tr class="thead-inverse">
                                            <th>Sr No</th>
                                            <th>Team name</th>
                                        </tr>
                                        {% for k in team_per_pool %}
                                            <tr>
                                                <td>{{ forloop.counter }}</td>
                                                <td>{% lookup all_teams j k max i %}</td>
                                            </tr>
                                        {% endfor %}
                                    </table>
                                </div>
                            {% endfor %}
                        </div>
                    {% endfor %}
                    {% if extra %}
                        <div class="row">

                            <div class="col-lg-6">
                                <table class="table table-bordered white">
                                    <tr>
                                        <th class="pool-title" colspan="2">
                                            <button style="width: 100%; height: 100%; background-color: inherit; padding: 5px; border: none"
                                                    class="pool-title" name="Pool" value="{{ extra|add:"1" }}">
                                                Pool {{ extra|add:"1" }}</button>
                                        </th>
                                    </tr>
                                    <tr class="thead-inverse">
                                        <th>Sr No</th>
                                        <th>Team name</th>
                                    </tr>
                                    {% for k in team_per_pool %}
                                        <tr>
                                            <td>{{ forloop.counter }}</td>
                                            <td>{% lookup all_teams extra k max %}</td>
                                        </tr>
                                    {% endfor %}
                                </table>
                            </div>

                        </div>
                    {% endif %}
                </form>
            </div>
        </div>
    </div>
{% endblock %}